name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
          
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore NuGet Packages
      run: dotnet restore src\RagnaCustoms.sln

    - name: Restore NuGet Packages
      run: nuget restore src\RagnaCustoms.sln
         
    - name: Build Solution
      run: msbuild src\RagnaCustoms.sln /p:Configuration=Release
      
    - name: Publish Solution
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Latest build"
        files: |
          RagnaCustoms\bin\RagnaCustoms\*.dll
          RagnaCustoms\bin\RagnaCustoms\*.exe
          RagnaCustoms\bin\RagnaCustoms\*.config
