name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
          
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore NuGet Packages
      run: dotnet restore src\RagnaCustoms.sln
         
    - name: Restore msbuild
      run: msbuild src\RagnaCustoms.sln /t:restore

    - name: Build Solution
      run: msbuild /nologo src\RagnaCustoms.sln /p:Configuration=Release /p:Platform="Any CPU" /p:Verbose=True
      
    - name: Prepare Zip
      uses: papeloto/action-zip@v1
      with:
        files: src\RagnaCustoms.App\bin\Release
        dest:  RagnaCustoms.zip

    - name: Publish Solution
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Latest build"
        files: |
          src\RagnaCustoms.Installer2\bin\Release\RagnaCustoms.Installer2.msi
          RagnaCustoms.zip
